# Based on the tutorial https://bencher.dev/docs/how-to/github-actions/

on:
  push:
    branches: main
    paths:
      - '**/*.rs'
      - 'rust/Cargo.toml'
      - 'rust/Cargo.lock'
  schedule:
    # Run once a month (random values for minute, hour, day; any month or day)
    - cron: "3 1 4 * *"
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  benchmark_base_branch:
    # Run only on the upstream repository.
    if: github.repository == 'google/sedpack'
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: Installing sedpack pip package
        run: |
          pip install sedpack
      - name: Prepare benchmarking data
        working-directory: ./rust
        run: bash benches/setup.sh
      - uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c  # v1.15.2
      - uses: bencherdev/bencher@8151077aa7b1bceaac11c4b308265417cae60e2b  # v0.5.10
      - name: Track base branch benchmarks with Bencher
        working-directory: ./rust
        run: |
          bencher run \
          --project sedpack \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-upper-boundary 0.99 \
          --thresholds-reset \
          --err \
          --adapter rust_criterion \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          "cargo bench"
